select
    cast(source_row_number as bigint) as source_row_number,
    trim(CIRCUIT) as circuit_code,
    trim(DISTRICT) as district_code,
    trim(OFFICE) as office_code,
    trim(DOCKET) as docket_number,
    trim(ORIGIN) as origin_code,
    filed_date_parsed as filed_date,
    {{ parse_fjc_date('FDATEUSE') }} as filed_date_used_by_ao,
    trim(JURIS) as jurisdiction_code,
    trim(NOS) as nature_of_suit_raw,
    trim(TITL) as title_raw,
    trim(SECTION) as section_raw,
    trim(SUBSECT) as subsection_raw,
    trim(RESIDENC) as residence_raw,
    trim(JURY) as jury_demand_raw,
    trim(CLASSACT) as class_action_raw,
    trim(DEMANDED) as amount_demanded_raw,
    trim(COUNTY) as county_raw,
    trim(ARBIT) as arbitration_raw,
    trim(MDLDOCK) as mdl_docket_raw,
    trim(TRANSDAT) as transfer_date_raw,
    trim(TRANSOFF) as transfer_office_raw,
    trim(TRANSDOC) as transfer_docket_raw,
    trim(TRANSORG) as transfer_origin_raw,
    trim(TERMDATE) as termination_date_raw,
    {{ parse_fjc_date('TERMDATE') }} as termination_date_source,
    {{ parse_fjc_date('TDATEUSE') }} as termination_date_used_by_ao,
    trim(TRCLACT) as termination_class_action_raw,
    trim(PROCPROG) as procedural_progress_code,
    trim(DISP) as disposition_code,
    trim(NOJ) as judgment_nature_raw,
    trim(AMTREC) as amount_received_raw,
    trim(JUDGMENT) as judgment_raw,
    trim(DJOINED) as issue_joined_date_raw,
    trim(PRETRIAL) as pretrial_date_raw,
    trim(TRIBEGAN) as trial_begin_date_raw,
    trim(TRIALEND) as trial_end_date_raw,
    trim(TRMARB) as termination_arbitration_raw,
    trim(PROSE) as pro_se_raw,
    trim(IFP) as fee_status_raw,
    trim(STATUSCD) as status_code,
    trim(TAPEYEAR) as statistical_year,
    source_snapshot_cutoff,
    source_digest,
    cast(raw_contract_version as bigint) as raw_contract_version,
    cast(filing_year as bigint) as filing_year
from {{ source('raw_fjc', 'civil_records') }}
